### ISSUE TITLE
Can't open the shapefiles

### ISSUE THREAD

**Issue by TwoBee** [sergiocostafh/ggplot2_dataviz#1]
So I tried your code and whenever I try to read the files I get an error

> The file doesn't seem to exist.

And when I try to open the .shp alone I get

> Error: `x` must be a vector, not a `sfc_MULTIPOLYGON/sfc` object.

I'm fairly new to R and I really don't know what to do right now. 
But I run on R3.6 and every lib is up to date

**Comment by sergiocostafh** [comment]
The command
`br_mun <- read_sf('./shapefile','br_municipios')`
will search for a .shp file named "br_municipios" in a folder named "shapefile" that must be in the working directory of your R project.

Use the command getwd() to see your working directory. The "shapefile" folder must be there.
