### ISSUE TITLE
hello, I'm sorry, I don't understand anything at all in this program, but I need to get a credit in mathematics, could you tell me why the script does not work for me (in the program I work for the first time)

### ISSUE THREAD

**Issue by Polinp** [sergiocostafh/ggplot2_dataviz#3]
![help](https://user-images.githubusercontent.com/85704242/121581521-5a376280-ca47-11eb-9d34-a4c4d40ab3d7.png)

**Comment by sergiocostafh** [comment]
Hi, in lines 4 and 5 you need to change the \ (back slash) for / (forward slash), that's how R can understand the paths we give.
You also need to enclose the text on line 5 between quotes, because paths must be passed as strings.

Hope it helps.
